[workspace]
members = ["programs/seller-dao"]

[programs.localnet]
seller_dao = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test --prefix programs/seller-dao"

[toolchain]
anchor_version = "0.29.0"

[test.validator]
bind_address = "127.0.0.1"
gossip_port = 8020
dynamic_port_range = "8021-8050"
